### ISSUE TITLE
Doesn't load the mod

### ISSUE THREAD

**Issue by lexein** [blackd/Inventory-Profiles#159]
I get this error in version 1.19
Caused by: org.anti_ad.a.b.D: __glue_make_Identifier not initialized! This hard breaks stuff!
at org.anti_ad.mc.common.vanilla.render.glue.TextureKt$__glue_make_Identifier$1.invoke(Unknown Source) ~[InventoryProfilesNext-forge-1.19-1.5.3.jar%23144!/:?] {re:classloading}
	at org.anti_ad.mc.common.vanilla.render.glue.TextureKt$__glue_make_Identifier$1.invoke(Unknown Source) ~[InventoryProfilesNext-forge-1.19-1.5.3.jar%23144!/:?] {re:classloading}
	at org.anti_ad.mc.common.vanilla.render.glue.IdentifierHolder.<init>(Unknown Source) ~[InventoryProfilesNext-forge-1.19-1.5.3.jar%23144!/:?] {re:classloading}
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.<clinit>(Unknown Source) ~[InventoryProfilesNext-forge-1.19-1.5.3.jar%23144!/:?] {re:mixin,re:classloading}

**Comment by blackd** [comment]
update to the latest version of the mod.

forge made a breaking change at version 41.0.94 that makes it impossible to use versions of the mod prior 1.6.0

**Comment by lexein** [comment]
OK thank you

**Comment by lexein** [comment]
I already fixed the problem XD it was just because I didn't install kotlinforge sorry for bothering you as soon as I realized that the mod needs this to work correctly
