### ISSUE TITLE
Please Add 1.19.2 Forge Support

### ISSUE THREAD

**Issue by Jayryn** [blackd/Inventory-Profiles#165]
**Please add support for the latest 1.19.2 Forge Versions.**

**Forge Version:** 43.0.2

Crash on Startup
```
[08Aug2022 19:18:11.260] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Failed to initialize mod containers
net.minecraftforge.fml.ModLoadingException: Inventory Profiles Next has class loading errors
§7java.lang.reflect.InvocationTargetException: null
	at thedarkcolour.kotlinforforge.KotlinLanguageProvider$KotlinModTarget.loadMod(KotlinLanguageProvider.kt:55) ~[kotlinforforge-3.6.0-obf.jar%23148!/:3.6.0]
	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:276) ~[fmlcore-1.19.2-43.0.2.jar%23152!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:255) ~[fmlcore-1.19.2-43.0.2.jar%23152!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:257) ~[fmlcore-1.19.2-43.0.2.jar%23152!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:175) ~[fmlcore-1.19.2-43.0.2.jar%23152!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:91) ~[forge-1.19.2-43.0.2-universal.jar%23156!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19.2-43.0.2-universal.jar%23156!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:91) ~[forge-1.19.2-43.0.2-universal.jar%23156!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:468) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.0.2.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at thedarkcolour.kotlinforforge.KotlinLanguageProvider$KotlinModTarget.loadMod(KotlinLanguageProvider.kt:46) ~[kotlinforforge-3.6.0-obf.jar%23148!/:3.6.0]
	... 40 more
Caused by: java.lang.IncompatibleClassChangeError: Method 'net.minecraftforge.eventbus.api.BusBuilder net.minecraftforge.eventbus.api.BusBuilder.builder()' must be InterfaceMethodref constant
	at thedarkcolour.kotlinforforge.KotlinModContainer.<init>(KotlinModContainer.kt:40) ~[kotlinforforge-3.6.0-obf.jar%23148!/:3.6.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at thedarkcolour.kotlinforforge.KotlinLanguageProvider$KotlinModTarget.loadMod(KotlinLanguageProvider.kt:46) ~[kotlinforforge-3.6.0-obf.jar%23148!/:3.6.0]
	... 40 more
```

**Comment by blackd** [comment]
this looks more like kotlin for forge problem

**Comment by Jayryn** [comment]
> this looks more like kotlin for forge problem

I've reported it to them already and they said that it should be working for 1.19.2 -> I'll keep this issue updated once I know more.

**Link to the KotlinForForge Issue**
https://github.com/thedarkcolour/KotlinForForge/issues/46

KotlinForForge starts with 1.19.2 perfectly fine, but my game crashes once I use Inventory-Profiles-Next

**Comment by blackd** [comment]
I've tried with another kotlin mod "Inventorio" and got the same result. no IPN installed :)
so definitely Kotlin For Forge problem

**Comment by blackd** [comment]
I "LOVE" Forge... and their major changes in the middle of nothing :vomiting_face:

**Comment by Jayryn** [comment]
> I've tried with another kotlin mod "Inventorio" and got the same result. no IPN installed :)
> so definitely Kotlin For Forge problem 

Thanks for clarifying :3

**Comment by Jayryn** [comment]
> I "LOVE" Forge... and their major changes in the middle of nothing :vomiting_face: 

I've been there too, you'll get it done 👍
