### ISSUE TITLE
Immediate crash on opening Minecraft

### ISSUE THREAD

**Issue by Dupiter-AU** [blackd/Inventory-Profiles#187]
Inventory Profiles causes Exit Code 1 upon launching Minecraft Fabric 1.16.5 (Loader version 0.14.9).

Current list of mods:
```
	- blur 2.1.0
	- caffeineconfig 1.0.0 via sodium-extra
	- cloth-basic-math 0.6.1 via cloth-config2
	- cloth-config2 4.14.64
	- colormatic 2.2.9+mc.1.16.5
	- com_moandjiezana_toml_toml4j 0.7.2 via custom-fog
	- custom-fog 1.5.1
	- customspawns 0.6.1+1.16.5
	- entityculling 1.5.2
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via iris
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via iris
	- fabric-keybindings-v0 0.2.2+3cc0f0907d via fabric
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via sodium-extra
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-models-v0 0.3.1+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-indigo 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-rendering-v0 1.1.3+3cc0f0907d via fabric
	- fabric-rendering-v1 1.6.1+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via iris
	- fabric-screen-api-v1 1.0.1+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-textures-v0 1.0.7+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.14.9
	- ferritecore 2.1.0
	- here-be-no-dragons 1.0.0
	- hunger_remover 1.0.1
	- indium 1.0.0+mc1.16.5
	- inventoryprofilesnext 1.7.0
	- iris 1.2.7
	- java 8
	- lambdynlights 1.3.4+1.16
	- lazydfu 0.1.2
	- lithium 0.6.6
	- minecraft 1.16.5
	- modern_beta 2.8.3+1.16.5
	- modmenu 1.16.23
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- org_slf4j_slf4j-api 1.7.12 via iris
	- phosphor 0.8.0
	- reeses-sodium-options 1.4.7+mc1.16.5-build.56
	- satin 1.5.1 via blur
	- sodium 0.2.0+build.4
	- sodium-extra 0.4.8+mc1.16.5-build.53
	- spruceui 2.0.4+1.16 via lambdynlights
```

Crash log:
```
[16:54:22] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_437 has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_437 has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_202]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_202]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_202]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at net.minecraft.class_128.handler$zoe001$fillSystemDetails(class_128.java:1022) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) ~[fabric-loader-0.14.9-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
```

I am currently running on Linux if it helps.

**Comment by blackd** [comment]
which version of java do you have 

Linux should not be a problem I'm developing the mod on Linux

**Comment by blackd** [comment]
looks like fabric-language-kotlin requires minimum java 16
but I suggest you update java to 17

**Comment by Dupiter-AU** [comment]
yeah I don't have jre17-openjdk installed
I'll see if that works

**Comment by Dupiter-AU** [comment]
Nope; still crashing, even after reboot

**Comment by blackd** [comment]
can you post the full log

also what launcher are you using

**Comment by Dupiter-AU** [comment]
I'm using the AUR version of the minecraft launcher with Fabric installed on 1.16.5.
Here is the full log:
```
[18:23:57] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.9
[18:23:57] [main/INFO]: Loading 89 mods:
	- blur 2.1.0
	- caffeineconfig 1.0.0 via sodium-extra
	- cloth-basic-math 0.6.1 via cloth-config2
	- cloth-config2 4.14.64
	- colormatic 2.2.9+mc.1.16.5
	- com_moandjiezana_toml_toml4j 0.7.2 via custom-fog
	- custom-fog 1.5.1
	- customspawns 0.6.1+1.16.5
	- entityculling 1.5.2
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via iris
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via iris
	- fabric-keybindings-v0 0.2.2+3cc0f0907d via fabric
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via sodium-extra
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-models-v0 0.3.1+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-indigo 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-rendering-v0 1.1.3+3cc0f0907d via fabric
	- fabric-rendering-v1 1.6.1+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via iris
	- fabric-screen-api-v1 1.0.1+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-textures-v0 1.0.7+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.14.9
	- ferritecore 2.1.0
	- here-be-no-dragons 1.0.0
	- hunger_remover 1.0.1
	- indium 1.0.0+mc1.16.5
	- inventoryprofilesnext 1.7.0
	- iris 1.2.7
	- java 8
	- lambdynlights 1.3.4+1.16
	- lazydfu 0.1.2
	- lithium 0.6.6
	- minecraft 1.16.5
	- modern_beta 2.8.3+1.16.5
	- modmenu 1.16.23
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- org_slf4j_slf4j-api 1.7.12 via iris
	- phosphor 0.8.0
	- reeses-sodium-options 1.4.7+mc1.16.5-build.56
	- satin 1.5.1 via blur
	- sodium 0.2.0+build.4
	- sodium-extra 0.4.8+mc1.16.5-build.53
	- spruceui 2.0.4+1.16 via lambdynlights
[18:23:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/dupiter/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:23:58] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
[18:23:58] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[18:23:58] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[18:23:58] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[18:23:59] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_437 has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_437 has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_202]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_202]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_202]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at net.minecraft.class_128.handler$zoe001$fillSystemDetails(class_128.java:1022) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) ~[fabric-loader-0.14.9-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
```

**Comment by Dupiter-AU** [comment]
If Fabric Kotlin depends on a more up-to-date version of Java I don't see any reason why it doesn't cause a crash too. It's fully functioning, because Hunger Remover depends upon it

**Comment by blackd** [comment]
in the log you are still using java 8

**Comment by Dupiter-AU** [comment]
That shouldn't be happening. I have the latest version of Java installed, so I have no idea why it's deciding to use that version

**Comment by Dupiter-AU** [comment]
```
Available Java environments:
  java-11-openjdk
  java-17-openjdk
  java-18-openjdk (default)
  java-8-openjdk/jre
```
java 18 is set to default

**Comment by blackd** [comment]
if it's the vanilla launcher it probably comes with it's own jre

I suggest switching to https://atlauncher.com/ it also has a very nice mod/pack  download and management tools

**Comment by Dupiter-AU** [comment]
Yeah, it seems like the launcher does come with it's own jre. Damn.
Personally, I actually prefer the official minecraft-launcher package, I took a look at ATLauncher, but it's not really catching my eye.
Thanks for all the help, I'll close the issue now. Sorry for the time waste.

**Comment by blackd** [comment]
if the problem is caused by IPN it will be resolved in the next release.
