### ISSUE TITLE
Index out of bounds with open chest and profile switching

### ISSUE THREAD

**Issue by Remodor** [blackd/Inventory-Profiles#240]
When switching the profile while looking in an open chest I get an index out of bounds exception. Tried it with different profiles. Happens most of the times. If more information is needed, let me know. 

Thank you!

```
Unreported exception thrown!
java.lang.IndexOutOfBoundsException: Index 56 out of bounds for length 46
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at org.anti_ad.mc.ipnext.event.ProfileSwitchHandler$ProfileMonitor.findAndSwap(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ProfileSwitchHandler.applyProfile(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ProfileSwitchHandler.onTickInGame(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ClientEventHandler.onTickInGame(Unknown Source)
	at org.anti_ad.mc.ipnext.event.ClientEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zlo000$tick2(class_310.java)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by blackd** [comment]
Well I've never tested it with opened chest but it makes lots of sense to be able to apply a profile from a chest.

But making it pickup items from chests will require substantial changes.....

I'll definitely fix the exception but I'm not sure it will start picking items from the opened chest.

**Comment by Aesthir** [comment]
I get the same error with MC 1.21.1 (fabric). Irrespective of whether IPN grabs items from a chest, switching profiles should not crash the client at any time. You can leave it not grabbing items from chests, but the crashing business makes profile switching basically unusable in some guis.

https://mclo.gs/vasHNvw

**Comment by blackd** [comment]
The thing is that so far I haven't been able to recreate the crash.
And this issue has been low priority because of the hoops players must go to even make it possible to switch profiles while a chest is opened. Yes probably 90% of the players don't know you can change the shortcuts to work when a GUI is shown :).

So in the next release it will be impossible to switch profiles while the opened GUI is not the player inventory. This is because the gear slots are not available in that case.
