### ISSUE TITLE
[1.16.5 fabric] Conflict with Modern Industrialization

### ISSUE THREAD

**Issue by znena** [blackd/Inventory-Profiles#243]
I opened MI Steam boiler, and Minecraft crashed.

Description: Rendering screen

java.lang.NullPointerException: inventory must not be null
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.getSlotLocations(Unknown Source)
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.drawSprite(Unknown Source)
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.onBackgroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
	at net.minecraft.class_465.handler$bak000$onBackgroundRender(class_465.java)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at aztech.modern_industrialization.machines.MachineScreenHandlers$ClientScreen.method_25394(MachineScreenHandlers.java:280)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

Here is the version of the mod:
 libIPN-fabric-1.16-1.0.6.jar
 InventoryProfilesNext-fabric-1.16-1.8.5
 Modern-Industrialization-0.4.0-alpha.11

Is there any way to disable IPN in a specified GUI?

**Comment by blackd** [comment]
this seams to be caused by MI
the ui should provide inventory if it's extending the vanilla class

**Comment by blackd** [comment]
v1.8.6  has implemented possible workaround for this. please test
