### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by sudapeople** [blackd/Inventory-Profiles#276]
I am using ipn 1.9.2 and libipn 2.0.2.
But this message is output.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install libipn, any version between 2.0.2 (inclusive) and 3.0.0 (exclusive).
Unmet dependency listing:
	 - Mod 'Inventory Profiles Next' (inventoryprofilesnext) 1.9.2 requires any version between 2.0.2 (inclusive) and 3.0.0 (exclusive) of libipn, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by blackd** [comment]
my guess is that you have installed the forge version of libipn

**Comment by blackd** [comment]
if you by any chance have installed the proper version of libIPN then this will be a fabric problem not IPN

**Comment by blackd** [comment]
I will interpret your silence like I'm right and you indeed downloaded the wrong version and will close the issue
