### ISSUE TITLE
Rendering screen java.util.NoSuchElementException causes crash

### ISSUE THREAD

**Issue by LichLord91** [blackd/Inventory-Profiles#321]
Here's log file with all the info 

https://mclo.gs/YgRqG6i 

Adding in some info in case logs get nuked

```
<html>
<body>
<!--StartFragment-->

13:34:25] [Render thread/ERROR]: Reported exception thrown!
--
519 | net.minecraft.class_148: Rendering screen
520 | at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:946) ~[client-intermediary.jar:?]
521 | at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218) ~[client-intermediary.jar:?]
522 | at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801) ~[client-intermediary.jar:?]
523 | at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
524 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
525 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
526 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
527 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
528 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
529 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
530 | Caused by: java.util.NoSuchElementException
531 | at java.util.ArrayDeque.getLast(ArrayDeque.java:413) ~[?:?]
532 | at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack.java:71) ~[client-intermediary.jar:?]
533 | at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:86) ~[client-intermediary.jar:?]
534 | at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:82) ~[client-intermediary.jar:?]
535 | at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
536 | at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
537 | at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
538 | at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
539 | at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
540 | at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.5.jar:?]
541 | at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.5.jar:?]
542 | at net.minecraft.class_465.handler$bcc000$inventoryprofilesnext$onBackgroundRender(class_465.java) ~[client-intermediary.jar:?]
543 | at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:98) ~[client-intermediary.jar:?]
544 | at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:28) ~[client-intermediary.jar:?]
545 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:92) ~[client-intermediary.jar:?]
546 | at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:121) ~[client-intermediary.jar:?]
547 | at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:937) ~[client-intermediary.jar:?]
548 | ... 9 more
549 | ---- Minecraft Crash Report ----
550 | // Hi. I'm Minecraft, and I'm a crashaholic.
551 | Time: 2023-04-14 13:34:25
552 | Description: Rendering screen
553 | java.util.NoSuchElementException
554 | at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
555 | at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack.java:71)
556 | at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:86)
557 | at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:82)
558 | at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54)
559 | at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93)
560 | at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98)
561 | at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109)
562 | at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58)
563 | at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source)
564 | at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
565 | at net.minecraft.class_465.handler$bcc000$inventoryprofilesnext$onBackgroundRender(class_465.java)
566 | at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:98)
567 | at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:28)
568 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:92)
569 | at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:121)
570 | at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:937)
571 | at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218)
572 | at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801)
573 | at net.minecraft.client.main.Main.main(Main.java:237)
574 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
575 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
576 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
577 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
578 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
579 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
580 | A detailed walkthrough of the error, its code path and all known details is as follows:
581 | ---------------------------------------------------------------------------------------
582 | -- Head --
583 | Thread: Render thread
584 | Stacktrace:
585 | at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
586 | at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack.java:71)
587 | at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:86)
588 | at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:82)
589 | at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54)
590 | at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93)
591 | at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98)
592 | at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109)
593 | at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58)
594 | at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source)
595 | at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
596 | at net.minecraft.class_465.handler$bcc000$inventoryprofilesnext$onBackgroundRender(class_465.java)
597 | at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:98)
598 | at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:28)
599 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:92)
600 | at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:121)
601 | -- Screen render details --
602 | Details:
603 | Screen name: net.minecraft.class_490
604 | Mouse location: Scaled: (234, 68). Absolute: (1171.000000, 342.000000)
605 | Screen size: Scaled: (512, 275). Absolute: (2560, 1373). Scale factor of 5.000000
606 | Stacktrace:
607 | at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:937)
608 | at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218)
609 | at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801)
610 | at net.minecraft.client.main.Main.main(Main.java:237)
611 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
612 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
613 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
614 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
615 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
616 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
617 | -- Affected level --
618 | Details:
619 | All players: 1 total; [class_746['LL91'/58143, l='ClientLevel', x=-523.73, y=67.00, z=163.80]]
620 | Chunk stats: 1024, 313
621 | Level dimension: minecraft:overworld
622 | Level spawn location: World: (-31,69,73), Section: (at 1,5,9 in -2,4,4; chunk contains blocks -32,-64,64 to -17,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
623 | Level time: 715967639 game time, 657863891 day time
624 | Server brand: Purpur
625 | Server type: Non-integrated multiplayer server
626 | Stacktrace:
627 | at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:455)
628 | at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2406)
629 | at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:820)
630 | at net.minecraft.client.main.Main.main(Main.java:237)
631 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
632 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
633 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
634 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
635 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
636 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
637 | -- Last reload --
638 | Details:
639 | Reload number: 1
640 | Reload reason: initial
641 | Finished: Yes
642 | Packs: vanilla, file/mullak99s-Faithful-32x-MC1.19.4-R1.zip, Fabric Mods
643 | -- System Details --
644 | Details:
645 | Minecraft Version: 1.19.4
646 | Minecraft Version ID: 1.19.4
647 | Operating System: Windows 10 (amd64) version 10.0
648 | Java Version: 17.0.6, Amazon.com Inc.
649 | Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
650 | Memory: 278093320 bytes (265 MiB) / 1551892480 bytes (1480 MiB) up to 4294967296 bytes (4096 MiB)
651 | CPUs: 24
652 | Processor Vendor: GenuineIntel
653 | Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
654 | Identifier: Intel64 Family 6 Model 151 Stepping 2
655 | Microarchitecture: Alder Lake

<!--EndFragment-->
</body>
</html>
```13:34:25] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:946) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.util.NoSuchElementException
	at java.util.ArrayDeque.getLast(ArrayDeque.java:413) ~[?:?]
	at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:82) ~[client-intermediary.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.5.jar:?]
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.5.jar:?]
	at net.minecraft.class_465.handler$bcc000$inventoryprofilesnext$onBackgroundRender(class_465.java) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:937) ~[client-intermediary.jar:?]
	... 9 more
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.
Time: 2023-04-14 13:34:25
Description: Rendering screen
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack.java:71)
	at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:86)
	at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:82)
	at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54)
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93)
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98)
	at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109)
	at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58)
	at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
	at net.minecraft.class_465.handler$bcc000$inventoryprofilesnext$onBackgroundRender(class_465.java)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:98)
	at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:28)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:92)
	at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:121)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:937)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack.java:71)
	at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:86)
	at net.minecraft.client.gui.DrawableHelper.fill(DrawableHelper.java:82)
	at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54)
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93)
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98)
	at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109)
	at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58)
	at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
	at net.minecraft.class_465.handler$bcc000$inventoryprofilesnext$onBackgroundRender(class_465.java)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:98)
	at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:28)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:92)
	at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:121)
-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (234, 68). Absolute: (1171.000000, 342.000000)
	Screen size: Scaled: (512, 275). Absolute: (2560, 1373). Scale factor of 5.000000
Stacktrace:
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:937)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Affected level --
Details:
	All players: 1 total; [class_746['LL91'/58143, l='ClientLevel', x=-[523](https://mclo.gs/YgRqG6i#L523).73, y=67.00, z=163.80]]
	Chunk stats: 1024, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (-31,69,73), Section: (at 1,5,9 in -2,4,4; chunk contains blocks -32,-64,64 to -17,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 715967639 game time, 657863891 day time
	Server brand: Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:455)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2406)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/mullak99s-Faithful-32x-MC1.19.4-R1.zip, Fabric Mods
-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 278093320 bytes (265 MiB) / 1[551](https://mclo.gs/YgRqG6i#L551)892480 bytes (1480 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake

**Comment by blackd** [comment]
I would start by removing exordium
and testing again

if this doesn't work also remove sodium.

And whichever fixes it report the problem to them.
because the exception is coming from minecraft classes that both of these mess with.
