### ISSUE TITLE
[1.20.1] Sorting inventory when Apotheosis gems are present results in errors in chat. (Unequal before and after item counts.)

### ISSUE THREAD

**Issue by Gbergz** [blackd/Inventory-Profiles#356]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Forge

### Modloader Version

Forge: 47.1.3

### Operating System

Windows

### List of all other installed mods

![screenshot](https://github.com/blackd/Inventory-Profiles/assets/26634554/d2a201f6-fd93-4af5-a8ce-7d0da8152dd1)

### Describe the problem

With Apotheosis installed. There's errors in chat when attempting to sort inventory with Gems present in inventory.
`(java.lang.IllegealStateException: Unequal before and after item counts.)`

### Steps to reproduce

1. Acquire any Apotheosis gems from chests / mobs around the world.
2. Open inventory.
    (have the gem in inventory when sorting)
3. Attempt to sort inventory with buttons or keybind.
4. See error in chat. Sorting failed: `(java.lang.IllegealStateException: Unequal before and after item counts.)`
5. Profit.

### Logs
https://gist.githubusercontent.com/Gbergz/d181a9483668a0d465751882b0105a2c/raw/08b5cab755c0a09ef028f4374cf442d98f39f45f/gistfile1.txt

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [ ] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
my guess is you got stacked unstackable items from the chest. 
try unstacking them

**Comment by Gbergz** [comment]
They're not stacked. Single piece gems

**Comment by blackd** [comment]
post a screenshot of the inventory that doesn't sort

**Comment by Gbergz** [comment]
Not at the PC right now, but its two gems, found in chests in the world. And some logs & planks.

Edit: Happens most often when inventory is shuffled with items and then sorting with the keybind and the Z sorting button.

**Comment by blackd** [comment]
still I prefer if you post a screenshot

**Comment by Gbergz** [comment]
🤷 

Will be posted in a bit.

**Comment by Gbergz** [comment]
Here's a video
https://streamable.com/ngnuf7

**Comment by taiyoko** [comment]
I got a similar error message, but seems to be tied to a Corail Tombstone scroll, here the relevant excerpt from my logs (modpack is ATM9)

> [04:51:08] [Render thread/WARN] [Inventory Profiles Next/]: [Inventory Profiles Next] Item tombstone:magic_scroll not present in the Creative Inventory Search Tab!
> [04:51:08] [Render thread/WARN] [Inventory Profiles Next/]: [Inventory Profiles Next] Item tombstone:magic_scroll not present in the Creative Inventory Search Tab!
> [04:51:08] [Render thread/WARN] [Inventory Profiles Next/]: [Inventory Profiles Next] Item tombstone:magic_scroll not present in the Creative Inventory Search Tab!
> [04:51:08] [Render thread/WARN] [Inventory Profiles Next/]: [Inventory Profiles Next] Item tombstone:magic_scroll not present in the Creative Inventory Search Tab!
> [04:51:08] [Render thread/WARN] [Inventory Profiles Next/]: [Inventory Profiles Next] Item tombstone:magic_scroll not present in the Creative Inventory Search Tab!
> [04:51:08] [Render thread/WARN] [Inventory Profiles Next/]: [Inventory Profiles Next] Item tombstone:magic_scroll not present in the Creative Inventory Search Tab!
> [04:51:08] [Render thread/WARN] [Inventory Profiles Next/]: [Inventory Profiles Next] Item tombstone:magic_scroll not present in the Creative Inventory Search Tab!
> java.lang.IllegalStateException: Unequal before and after item counts
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.sandbox.ItemPlanner.tracker(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.AdvancedContainer.tracker(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.AdvancedContainer$Companion.tracker(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.AdvancedContainer$Companion.tracker$default(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.InnerActions.innerDoSort(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.InnerActions.doSort(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.GeneralInventoryActions.doSort(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.GeneralInventoryActions.doSort(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.inventory.GeneralInventoryActions.doSort$default(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.input.InventoryInputHandler.onInput(Unknown Source)
> 	at TRANSFORMER/inventoryprofilesnext@1.10.7/org.anti_ad.mc.ipnext.input.InputHandler.onInput(Unknown Source)
> 	at TRANSFORMER/libipn@4.0.0/org.anti_ad.mc.common.input.GlobalInputHandler.onInput(GlobalInputHandler.kt:114)
> 	at TRANSFORMER/libipn@4.0.0/org.anti_ad.mc.common.input.GlobalInputHandler.onKey(GlobalInputHandler.kt:91)
> 	at TRANSFORMER/libipn@4.0.0/org.anti_ad.mc.common.input.GlobalInputHandler.onMouseButton(GlobalInputHandler.kt:209)
> 	at TRANSFORMER/libipn@4.0.0/org.anti_ad.mc.common.forge.CommonForgeEventHandler.onScreenMouseButton(CommonForgeEventHandler.java:126)
> 	at TRANSFORMER/libipn@4.0.0/org.anti_ad.mc.common.forge.CommonForgeEventHandler.onMouseClicked(CommonForgeEventHandler.java:100)
> 	at TRANSFORMER/libipn@4.0.0/org.anti_ad.mc.common.forge.__CommonForgeEventHandler_onMouseClicked_Pre.invoke(.dynamic)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
> 	at TRANSFORMER/forge@47.1.3/net.minecraftforge.client.ForgeHooksClient.onScreenMouseClickedPre(ForgeHooksClient.java:612)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:90)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188)
> 	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
> 	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
> 	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
> 	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
> 	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
> 	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
> 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
> [04:51:08] [Render thread/INFO] [minecraft/ChatComponent]: [CHAT] java.lang.IllegalStateException: Unequal before and after item counts

**Comment by blackd** [comment]
hmm the thing that is missing in the creative inventory search is the problem

**Comment by Kata1337** [comment]
I think the gems and scrolls from Apotheosis and Corail Tombstone are created dynamically, with varying properties, so they won't be in the creative inventory...

**Comment by blackd** [comment]
any idea how to create some so I can test?

**Comment by jinkhya** [comment]
Hello you can do : 
`/loot give @p loot minecraft:chests/abandoned_mineshaft`
Run it a couple times and you'll get gems from apotheosis rather quickly. To reproduce the error you need 2-4 of them in a chest.

**Comment by Gbergz** [comment]
Any updates on this?
In 1.19.2 this wasn't an issue, iirc.

**Comment by blackd** [comment]
I don't have time to work on the mod at the moment.

**Comment by Gbergz** [comment]
Gotcha, no worries!

**Comment by Phoupraw** [comment]
I met the same error, too.

Here is the command to place the chest with items.
```
/setblock ~ ~ ~ minecraft:chest{Items:[{Count:1b,Slot:0b,id:"minecraft:turtle_helmet",tag:{Damage:0,affix_data:{affixes:{"apotheosis:armor/attribute/fortunate":0.58189046f,"apotheosis:armor/attribute/ironforged":0.0690096f,"apotheosis:armor/attribute/stalwart":0.7485494f,"apotheosis:armor/dmg_reduction/runed":0.7102695f,"apotheosis:durable":0.08f},name:'{"color":"#5555FF","translate":"misc.apotheosis.affix_name.three","with":[{"translate":"affix.apotheosis:armor/attribute/ironforged"},"",{"translate":"affix.apotheosis:armor/attribute/fortunate.suffix"}]}',rarity:"apotheosis:rare",sockets:1},apoth_rchest:1b}},{Count:1b,Slot:1b,id:"minecraft:chainmail_leggings",tag:{Damage:0,affix_data:{affixes:{"apotheosis:armor/attribute/blessed":0.6915807f,"apotheosis:armor/attribute/ironforged":0.39979088f},name:'{"color":"#33FF33","translate":"misc.apotheosis.affix_name.three","with":[{"translate":"affix.apotheosis:armor/attribute/blessed"},"",{"translate":"affix.apotheosis:armor/attribute/ironforged.suffix"}]}',rarity:"apotheosis:uncommon",sockets:1,uuids:[[I;1148128168,-1665710865,-2046254071,1467589615]]},apoth_rspawn:1b}},{Count:1b,Slot:2b,id:"minecraft:golden_leggings",tag:{Damage:0,Enchantments:[{id:"apotheosis:icy_thorns",lvl:3s}]}},{Count:1b,Slot:3b,id:"apotheosis:gem",tag:{affix_data:{rarity:"apotheosis:rare"},gem:"apotheosis:core/combatant"}},{Count:1b,Slot:4b,id:"apotheosis:gem",tag:{affix_data:{name:'{"color":"#33FF33","translate":"%s","with":[{"text":""}]}',rarity:"apotheosis:uncommon"},gem:"apotheosis:core/breach"}},{Count:1b,Slot:5b,id:"apotheosis:gem",tag:{affix_data:{rarity:"apotheosis:common"},gem:"apotheosis:core/warlord"}},{Count:1b,Slot:6b,id:"minecraft:iron_chestplate",tag:{Damage:25,affix_data:{affixes:{"apotheosis:armor/attribute/blessed":0.00984776f},name:'{"color":"#808080","translate":"misc.apotheosis.affix_name.two","with":[{"translate":"affix.apotheosis:armor/attribute/blessed"},"",""]}',rarity:"apotheosis:common",uuids:[[I;-1033874251,1164200406,-1189088052,926965163]]},apoth_rspawn:1b}},{Count:1b,Slot:7b,id:"minecraft:trident",tag:{Damage:0,affix_data:{affixes:{"apotheosis:durable":0.16f,"apotheosis:ranged/attribute/agile":0.60594314f,"apotheosis:ranged/mob_effect/ensnaring":0.76785785f,"apotheosis:sword/attribute/elongated":0.1147567f,"apotheosis:sword/attribute/lacerating":0.35439456f,"apotheosis:sword/mob_effect/weakening":0.8845854f},name:'{"color":"#5555FF","translate":"misc.apotheosis.affix_name.three","with":[{"translate":"affix.apotheosis:ranged/mob_effect/ensnaring"},"",{"translate":"affix.apotheosis:sword/attribute/elongated.suffix"}]}',rarity:"apotheosis:rare",sockets:1,uuids:[[I;-133158044,1342458011,-1894239298,-610149817]]},apoth_rchest:1b}},{Count:1b,Slot:8b,id:"apotheosis:gem",tag:{affix_data:{rarity:"apotheosis:common"},gem:"apotheosis:core/slipstream"}},{Count:1b,Slot:9b,id:"minecraft:chainmail_helmet",tag:{Damage:38,Enchantments:[{id:"minecraft:unbreaking",lvl:3s},{id:"minecraft:protection",lvl:2s}],affix_data:{affixes:{"apotheosis:armor/attribute/blessed":0.22949952f,"apotheosis:armor/attribute/ironforged":0.7748402f},name:'{"italic":false,"color":"#33FF33","translate":"misc.apotheosis.affix_name.four","with":["Derrel\'s",{"translate":"affix.apotheosis:armor/attribute/ironforged"},"",{"translate":"affix.apotheosis:armor/attribute/blessed.suffix"}]}',rarity:"apotheosis:uncommon",uuids:[[I;231376543,501760074,-1377097123,1595326452]]},apoth_boss:1b,display:{Name:'{"extra":[{"text":"Sallet"}],"text":""}'}}},{Count:1b,Slot:10b,id:"minecraft:chainmail_boots",tag:{Damage:135,Enchantments:[{id:"minecraft:feather_falling",lvl:3s}]}},{Count:1b,Slot:11b,id:"minecraft:iron_shovel",tag:{Damage:5,affix_data:{affixes:{"apotheosis:breaker/attribute/destructive":0.3493281f,"apotheosis:breaker/attribute/experienced":0.41696393f,"apotheosis:breaker/attribute/lengthy":0.06534284f,"apotheosis:breaker/special/radial":0.860001f,"apotheosis:durable":0.12f},name:'{"color":"#5555FF","translate":"misc.apotheosis.affix_name.three","with":[{"translate":"affix.apotheosis:breaker/attribute/destructive"},"",{"translate":"affix.apotheosis:breaker/attribute/lengthy.suffix"}]}',rarity:"apotheosis:rare",sockets:2,uuids:[[I;-412205526,-942784034,-1804223438,-1409344959]]},apoth_rspawn:1b}},{Count:1b,Slot:12b,id:"minecraft:iron_leggings",tag:{Damage:0,affix_data:{affixes:{"apotheosis:armor/attribute/fortunate":0.91006255f,"apotheosis:armor/attribute/ironforged":0.5803315f,"apotheosis:armor/attribute/spiritual":0.056647897f,"apotheosis:armor/dmg_reduction/dwarven":0.3362605f,"apotheosis:durable":0.09f},name:'{"color":"#5555FF","translate":"misc.apotheosis.affix_name.three","with":[{"translate":"affix.apotheosis:armor/dmg_reduction/dwarven"},"",{"translate":"affix.apotheosis:armor/attribute/fortunate.suffix"}]}',rarity:"apotheosis:rare",sockets:2},apoth_merchant:1b}},{Count:1b,Slot:13b,id:"minecraft:chainmail_boots",tag:{Damage:9,affix_data:{affixes:{"apotheosis:armor/attribute/fortunate":0.35664386f,"apotheosis:armor/attribute/ironforged":0.97499657f,"apotheosis:armor/attribute/steel_touched":0.79409796f,"apotheosis:armor/dmg_reduction/feathery":0.22731483f,"apotheosis:durable":0.12f},name:'{"color":"#5555FF","translate":"misc.apotheosis.affix_name.three","with":[{"translate":"affix.apotheosis:armor/dmg_reduction/feathery"},"",{"translate":"affix.apotheosis:armor/attribute/ironforged.suffix"}]}',rarity:"apotheosis:rare",sockets:1,uuids:[[I;1643869066,2054506844,-1658570554,-290886186]]},apoth_rspawn:1b}},{Count:1b,Slot:14b,id:"minecraft:trident",tag:{Damage:0,affix_data:{affixes:{"apotheosis:durable":0.060000002f,"apotheosis:ranged/attribute/windswept":0.37222224f,"apotheosis:ranged/mob_effect/grievous":0.5287352f,"apotheosis:sword/attribute/spellbreaking":0.5336607f,"apotheosis:sword/attribute/vampiric":0.5155784f},name:'{"color":"#5555FF","translate":"misc.apotheosis.affix_name.three","with":[{"translate":"affix.apotheosis:sword/attribute/spellbreaking"},"",{"translate":"affix.apotheosis:sword/attribute/vampiric.suffix"}]}',rarity:"apotheosis:rare",sockets:1,uuids:[[I;1298672648,-130462124,-1456761593,-1516410674]]},apoth_rspawn:1b}}]}
```

**Comment by PTALTS-LK** [comment]
same issue in fabric 0.16.4 minecraft 1.21

**Comment by asimard1** [comment]
I get this error again with this inventory, trying to send all items in the chest:
![image](https://github.com/user-attachments/assets/0b755d31-5bff-4fc3-a0c2-810f27beb72b)

**Comment by cfazilleau** [comment]
I was having the same issue using the latest version (2.0.4). downgrading to 2.0.0 fixed it (haven't tried all versions in-between)

**Comment by blackd** [comment]
> I was having the same issue using the latest version (2.0.4). downgrading to 2.0.0 fixed it (haven't tried all versions in-between)

yeah 2.0.0 doesn't really work when it compares NBT and component so the problem doesn't show.
Not to mention that moving and sorting don't work properly too.

**Comment by ODF4** [comment]
I'm getting the same error in chat (`java.lang.IllegalStateException: Unequal before and after item counts`) without having Apotheosis installed. Apparently the issue in my case is caused by the latest update of owo-lib.
I am able to replicate the issue consistently whenever both the latest version of IPN (2.0.4) and owo-lib (0.12.12) are installed at the same time. This issue does not happen if at least one of the two mods is downgraded to its previous version (IPN 2.0.3 and/or owo-lib 0.12.11).

My Minecraft version is 1.21.1, with Fabric API 0.104.0. The steps to reproduce the issue are the following:
- Install the following mods
![immagine](https://github.com/user-attachments/assets/d3f53162-404c-406a-b59e-36cbbfb5bbcd)
- Run Minecraft 1.21.1 and enter any world, in singleplayer or multiplayer
- Open a chest, and click the Move Matching Items button when there are items in the inventory which match the contents of the chest
![immagine](https://github.com/user-attachments/assets/9a9a214d-bf67-4950-9c10-9b7b24932f80)
- The error should now appear in chat (as you can somewhat see in the bottom corner of the chest screenshot)

I will gladly provide more information if needed. Thank you for your time, and thank you for developing such an amazing and convenient mod!

**Comment by ODF4** [comment]
Here's also the relevant part of one of my logs:
```
[...]
[18:29:00] [Render thread/WARN]: Class dev.emi.emi.screen.StackBatcher$UnlitFacade$Consumer does not support optimized vertex writing code paths, which may cause reduced rendering performance
[18:29:02] [Render thread/INFO]: [STDERR]: java.lang.IllegalStateException: Unequal before and after item counts
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.inventory.sandbox.ItemPlanner.tracker(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.inventory.AdvancedContainer.tracker(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.inventory.AdvancedContainer$Companion.tracker(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.inventory.AdvancedContainer$Companion.tracker$default(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.inventory.GeneralInventoryActions.doMoveMatch(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget$InitWidgets.moveAllToContainer$lambda$11(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.gui.widgets.IPNButtonWidget._init_$lambda$2(ButtonWidget.kt:45)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.gui.widgets.IPNButtonWidget.onClick(ButtonWidget.kt:55)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.gui.widgets.IPNButtonWidget.mouseClicked(ButtonWidget.kt:64)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.gui.inject.base.TexturedButtonWidget.mouseClicked(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.gui.widgets.IWidgetEventTarget$DefaultImpls.mouseClicked(Widget.kt:368)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.gui.widgets.IWidget$DefaultImpls.mouseClicked(Widget.kt:157)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.gui.widgets.Widget.mouseClicked(Widget.kt:46)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.ipnext.gui.inject.InsertWidgetHandler.mouseClicked(Unknown Source)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.input.GlobalScreenEventListener.onMouseClicked(GlobalScreenEventListener.kt:77)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.anti_ad.mc.common.input.GlobalScreenEventListener.onMouse(GlobalScreenEventListener.kt:196)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.handler$dki000$libipn$onScreenMouseButton(class_312.java:4062)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:107)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:196)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:108)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.redirect$ggm001$viafabricplus$storeEvent(class_312.java:8057)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:196)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:303)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1307)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:29:02] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:29:02] [Render thread/INFO]: [System] [CHAT] [18:29:02] java.lang.IllegalStateException: Unequal before and after item counts
[18:29:04] [Render thread/ERROR]: Something went wrong. Could not find JEI Search Text Field object
[...]
```

**Comment by asimard1** [comment]
I forgot to mention, I also do not have Apotheosis installed.

**Comment by ODF4** [comment]
> I forgot to mention, I also do not have Apotheosis installed.

Could owo-lib be the cause of the problem for you too? If not, I recommend that you remove your mods one by one (or better, half at a time) to find the one that is causing this issue (any new mods you installed/updated recently? Any libraries? Anything that affects the inventory in any way or adds new items?).

**Comment by blackd** [comment]
DON'T ADD COMMENTS TO ISSUES WHEN YOUR PROBLEM IS NOT RELATED TO THE ISSUE.

**Comment by blackd** [comment]
Same error doesn't mean the same issue. The title explicitly mentions specific conditions. So the issue is about the specific conditions.

**Comment by ODF4** [comment]
> Same error doesn't mean the same issue. The title explicitly mentions specific conditions. So the issue is about the specific conditions.

I'm really sorry about the comments, should I delete them and open a new issue in this case? That's what I wanted to do at first but I wrongly assumed it'd be marked as duplicate.

**Comment by blackd** [comment]
actually you should report this to owo not here since it is literally caused by their lib!

**Comment by Gbergz** [comment]
This is happening again on 1.21.1 NeoForge together with Apotheosis and its gems etc.

**Comment by Gbergz** [comment]
So it appears changing Sort Order config option from Item Count Descending to "Creative Menu" solves this.
