### ISSUE TITLE
Backup of villagers data failed! [1.16.5]

### ISSUE THREAD

**Issue by Object417** [blackd/Inventory-Profiles#368]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.16.5

### Modloader

Fabric

### Modloader Version

0.14.24

### Operating System

Windows

### List of all other installed mods

advancementinfo-1.16.5-fabric0.30.0-1.2
advdebug-2.3.0
alternate-current-mc1.16-1.7.0
antighost-1.16.5-fabric0.30.0-1.1.3
AnvilFix-1.2.1-1.16
appleskin-fabric-mc1.16.5-2.5.1
architectury-1.32.68
autoconfig1u-3.3.1
betterbeds-1.1.0
BetterF3-1.5.0-Fabric-1.16.5
bettermounthud-1.0.1
BetterPingDisplay-Fabric-1.16.5-1.1
block_limit_fix-1.0.4-fabric.5
chatlagfix-1.16.5+1.17.1-2.1.0
cleancut-mc1.16-2.1-fabric
cleardespawn-1.16.5-fabric0.30.0-1.1.1
cloth-config-4.17.101-fabric
collective-fabric-1.16.5-5.50
cullleaves-2.1.0
DripSounds-1.16-0.3.0
durabilityviewer-1.16.5-fabric0.30.0-1.10
dynamic-fps-3.2.1+minecraft-1.16.5-to-1.18.2
DynamicSoundFilters-1.2.0+1.16.5
EnchantedToolTips-1.3.5-1.16
enchlevel-langpatch-2.1.2
enhancedblockentities-0.4--1.16.x
entity_texture_features_fabric_1.16.5-4.3.1
entityculling-fabric-mc1.16.5-1.5.2
fabric-api-0.42.0+1.16
fabric-carpet-1.16.5-1.4.44+v210714
fabric-language-kotlin-1.10.13+kotlin.1.9.20
FallingTree-1.16.5-2.11.7
ferritecore-2.1.1-fabric
head-name-fix-1.16.5-1.2.0
indium-1.0.0+mc1.16.5
InventoryProfilesNext-fabric-1.16-1.10.6
iris-mc1.16.5-1.4.5
item-model-fix-1.0.3+1.16
justenoughkeys-0.5.3-fabric
krypton-0.1.2
lambdabettergrass-fabric-1.0.3+1.16
lambdynamiclights-fabric-1.3.4+1.16
lazydfu-0.1.2
letmedespawn-fabric-1.16-1.0.2
libIPN-fabric-1.16-3.0.2
lithium-fabric-mc1.16.5-0.6.6
memoryleakfix-fabric-pre1.17-1.1.2
mixintrace-1.0.0
modernfix-fabric-5.9.2+mc1.16.5
modmenu-1.16.23
nethermap-2.0.1-1.16.5
phosphor-fabric-mc1.16.2-0.8.0
reeses_sodium_options-1.6.3+mc1.16.5-build.86
replantingcrops-fabric_1.16.5-4.2
replaymod-1.16.4-2.6.13
RoughlyEnoughItems-5.12.385
sleepwarp-1.2.0+1.16.5
smoothboot-fabric-1.16.5-1.6.0
SmoothScrollingEverywhere-3.0.3-unstable
sodium-extra-0.4.18+mc1.16.5-build.96
sodium-fabric-mc1.16.5-0.2.0
TaxFreeLevels-1.1
titlefixer-1.0+1.16.5
translucencyfix-backport-2.1.0-fabric-quilt
vehiclefix-1.0
whats-that-slot-fabric-1.2.2+1.16.5
wthit-2.10.2-fabric
Xaeros_Minimap_23.8.4_Fabric_1.16.5
XaerosWorldMap_1.36.0_Fabric_1.16.5

### Describe the problem

```
[IPN VillagerDataManager/ERROR]: [Inventory Profiles Next] Backup of villagers data failed! This not a real problem but it will be very helpful if you can report it.
java.nio.file.AccessDeniedException: %appdata%\PrismLauncher\instances\%instance_name%\.minecraft\config\inventoryprofilesnext\%world_name%\villager-trading-config.json -> %appdata%\PrismLauncher\instances\%instance_name%\.minecraft\config\inventoryprofilesnext\%world_name%\prev-villager-trading-config.json
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_391]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_391]
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source) ~[?:1.8.0_391]
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source) ~[?:1.8.0_391]
	at java.nio.file.Files.move(Unknown Source) ~[?:1.8.0_391]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager.save(Unknown Source) [InventoryProfilesNext-fabric-1.16-1.10.6.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager.access$save(Unknown Source) [InventoryProfilesNext-fabric-1.16-1.10.6.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$task$1.invoke(Unknown Source) [InventoryProfilesNext-fabric-1.16-1.10.6.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$task$1.invoke(Unknown Source) [InventoryProfilesNext-fabric-1.16-1.10.6.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$lambda$4$$inlined$timer$1.run(Unknown Source) [InventoryProfilesNext-fabric-1.16-1.10.6.jar:?]
	at java.util.TimerThread.mainLoop(Unknown Source) [?:1.8.0_391]
	at java.util.TimerThread.run(Unknown Source) [?:1.8.0_391]
```

### Steps to reproduce

Talk to villagers in a village. Check the console regularly, and at some point the error will appear.

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by Object417** [comment]
Looks like the problem doesn't appear when there are no other mods installed.

**Comment by blackd** [comment]
Thank you for reporting this.

However, 1.16.x is no longer supported version of minecraft and the only solution to this "problem" I found out so far is to delete the original villager file and start over with the villager books marks. 
And this doesn't work every time.

**Comment by Jim3535** [comment]
I am seeing the same issue on 1.20.1 Fabric.

```
[12:20:22] [IPN VillagerDataManager/ERROR]: [Inventory Profiles Next] Backup of villagers data failed! This not a real problem but it will be very helpful if you can report it.
java.nio.file.AccessDeniedException: D:\Minecraft Instances\Prism\Meow SMP\.minecraft\config\inventoryprofilesnext\meow.mcserv.fun\villager-trading-config.json -> D:\Minecraft Instances\Prism\Meow SMP\.minecraft\config\inventoryprofilesnext\meow.mcserv.fun\prev-villager-trading-config.json
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
	at java.nio.file.Files.move(Files.java:1432) ~[?:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager.save(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager.access$save(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$task$1.invoke(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$task$1.invoke(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$lambda$4$$inlined$timer$1.run(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
	at java.util.TimerThread.run(Timer.java:516) ~[?:?]
[12:20:24] [IPN VillagerDataManager/ERROR]: [Inventory Profiles Next] Backup of villagers data failed! This not a real problem but it will be very helpful if you can report it.
java.nio.file.AccessDeniedException: D:\Minecraft Instances\Prism\Meow SMP\.minecraft\config\inventoryprofilesnext\meow.mcserv.fun\villager-trading-config.json -> D:\Minecraft Instances\Prism\Meow SMP\.minecraft\config\inventoryprofilesnext\meow.mcserv.fun\prev-villager-trading-config.json
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
	at java.nio.file.Files.move(Files.java:1432) ~[?:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager.save(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager.access$save(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$task$1.invoke(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$task$1.invoke(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at org.anti_ad.mc.ipnext.event.villagers.VillagerDataManager$saveIfDirty$lambda$4$$inlined$timer$1.run(Unknown Source) ~[InventoryProfilesNext-fabric-1.20-1.10.9.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
	at java.util.TimerThread.run(Timer.java:516) ~[?:?]
```

Mods:
  [✔] 1.20.x-preventer-1.0.0
  [✔] 3dskinlayers-fabric-1.5.4-mc1.20.1
  [✔] advancementscreenshot-1.20.1-4.3
  [✔] antighost-1.20-fabric0.83.0-1.1.5
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] architectury-9.1.12-fabric
  [✔] auto_third_person-fabric-1.20.1-2.1
  [✔] AutoElytra-2.1.0-1.20.1
  [✔] autofish-0.9.10-SNAPSHOT
  [✔] autoreconnect-2.2.0
  [✔] autototem-1.0
  [✔] balm-fabric-1.20.1-7.1.4
  [✔] bedrock-miner-1.20.1-1.2.1
  [✔] BetterAdvancements-Fabric-1.20.1-0.3.2.161
  [✔] betterbeds-1.3.0-1.19.3
  [✔] better-clouds-1.3.11+1.20.1
  [✔] BetterF3-7.0.2-Fabric-1.20.1
  [✔] BetterPingDisplay-Fabric-1.20.1-1.1.1
  [✔] block-entity-extended-rendering-3.0.0
  [✔] Bookshelf-Fabric-1.20.1-20.1.6
  [✔] chat_heads-0.10.23-fabric-1.20
  [✔] chesttracker-1.20.1-1.1.22
  [✔] chunksfadein-v1.0.4-1.20.1
  [✔] clear-enchanting-1.1.0
  [✔] clientcommands-2.8.5
  [✔] cloth-config-11.1.106-fabric
  [✔] collective-1.20.1-7.7
  [✔] Controlling-fabric-1.20.1-12.0.2
  [✔] Craftify-1.20.1-1.12.0-fabric
  [✔] craftingtweaks-fabric-1.20-18.2.1
  [✔] CullLessLeaves-1.3.0
  [✔] cupboard-fabric-1.20.1-2.1
  [✔] dark-loading-screen-1.6.14
  [✔] deathlog-0.3.2+1.20
  [✔] do-a-barrel-roll-3.3.7+1.20-fabric
  [✔] durabilitytooltip-1.1.5-fabric-mc1.20
  [✔] dynamiclights-v1.7-mc1.17x-1.20x-mod
  [✔] elytratime-2.0.0
  [✔] emi_loot-0.6.5+1.20.1
  [✔] emi-1.0.24+1.20.1+fabric
  [✔] emitrades-fabric-1.2.0+mc1.20.1
  [✔] EnchantmentDescriptions-Fabric-1.20.1-17.0.8
  [✔] enhanced_attack_indicator-1.0.4+1.20
  [✔] enhancedblockentities-0.9+1.20
  [✔] entityculling-fabric-1.6.2-mc1.20.1
  [✔] explosive-enhancement-1.2.2-1.20.x
  [✔] extremesoundmuffler-3.41-fabric-1.20
  [✔] fabric-api-0.90.7+1.20.1
  [✔] fabric-language-kotlin-1.10.14+kotlin.1.9.20
  [✔] fallingleaves-1.15.4+1.20.1
  [✔] ferritecore-6.0.1-fabric
  [✔] flowermap-1.3.0
  [✔] FogLooksGoodNow-1.2.0+1.20
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] FpsReducer2-fabric-1.20-2.5
  [✔] fuelinfo-1.1.0+1.20.1
  [✔] Gamma-Utils-1.7.16-mc1.20.1
  [✔] Iceberg-1.20.1-fabric-1.1.15
  [✔] ImmediatelyFast-1.2.7+1.20.2
  [✔] indium-1.0.27+mc1.20.1
  [✔] InventoryProfilesNext-fabric-1.20-1.10.9
  [✔] invhud.fabric.1.20-3.4.18
  [✔] iris-mc1.20.1-1.6.10
  [✔] iseelava-Fabric-1.20.1-1.1.7
  [✔] ItemBorders-1.20.1-fabric-1.2.0
  [✔] Jade-1.20-fabric-11.6.2
  [✔] jumpoverfences-fabric-1.20.1-1.3.0
  [✔] krypton-0.2.3
  [✔] lazydfu-0.1.3
  [✔] leaves-us-in-peace-1.0.17+MC1.20-1.20.1
  [✔] libIPN-fabric-1.20-4.0.1
  [✔] librarian-trade-finder-2.0.1
  [✔] litematica-enderchest-materials-0.0.4+1.20.1
  [✔] litematica-fabric-1.20.1-0.15.3
  [✔] litematica-printer-1.20.1-3.2.1
  [✔] litemoretica-1.2.5+mc1.20.1
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] lootbeams-1.0.3
  [✔] malilib-fabric-1.20.1-0.16.3
  [✔] map-in-slot-3.0.0
  [✔] memoryleakfix-fabric-1.17+-1.1.2
  [✔] minihud-fabric-1.20.1-0.27.0
  [✔] MixinConflictHelper-1.2.0
  [✔] modelfix-1.14-fabric
  [✔] modernfix-fabric-5.9.3+mc1.20.1
  [✔] modmenu-7.2.2
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] no-feeding-baby-1.2.0
  [✔] NoFog-1.3.4+1.16.5-1.20.1
  [✔] nvidium-0.2.3-beta
  [✔] owo-lib-0.11.2+1.20
  [✔] parachute-mc1.20-0.7.5
  [✔] particle-rain-2.0.8
  [✔] persistentinventorysearch-1.20.1-1.1
  [✔] physics-mod-pro-v159-fabric-1.20.1
  [✔] PickUpNotifier-v8.0.0-1.20.1-Fabric
  [✔] Prism-1.20.1-fabric-1.0.5
  [✔] PuzzlesLib-v8.1.8-1.20.1-Fabric
  [✔] recipe-unlocker-1.0.1
  [✔] reeses_sodium_options-1.6.5+mc1.20.1-build.95
  [✔] replaymod-1.20.1-2.6.13
  [✔] seamless-loading-screen-2.0.3+1.20.1-fabric
  [✔] Searchables-fabric-1.20.1-1.0.2
  [✔] serverpingerfixer-1.0.3
  [✔] shulkerboxtooltip-fabric-4.0.4+1.20.1
  [✔] simpleshulkerpreview-2.4.0
  [✔] skiptransitions-1.3.3+mc1.20
  [✔] sodium-extra-0.5.1+mc1.20.1-build.112
  [✔] sodium-fabric-mc1.20.1-0.5.3
  [✔] sodium-shadowy-path-blocks-3.2.1
  [✔] stack-to-nearby-chests-mc1.20.1-0.5.0
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] status-effect-bars-1.0.3
  [✔] stronghold-finder-1.0.1
  [✔] supermartijn642configlib-1.1.8a-fabric-mc1.20
  [✔] supermartijn642corelib-1.1.12d-fabric-mc1.20
  [✔] swingthrough-1.0.4+1.19
  [✔] symbol-chat-1.20.1-1.1.2
  [✔] syncmatica-1.20.1-0.3.11
  [✔] ToolStats-Fabric-1.20.1-16.0.4
  [✔] tooltipfix-1.1.1-1.20
  [✔] torohealth-1.20.1-fabric-1
  [✔] tweakeroo-fabric-1.20.1-0.17.1
  [✔] villagerarmor-5.0.1
  [✔] weaponmaster-client-only-fabric-1.20.1-3.0.5
  [✔] Xaeros_Minimap_23.8.4_Fabric_1.20
  [✔] xaeros-map-chest-tracker-integration-mc1.20.1-v1.0.2
  [✔] XaerosWorldMap_1.36.0_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.2.1+1.20

**Comment by blackd** [comment]
this was caused by windows defender but have since disappeared.
